apiVersion: v1
kind: Pod
metadata:
  name: limitado
  labels:
    resources: limitado
  annotations:
    resources: limitado
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          cpu: "0.3"
          memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
