apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  labels:
    resources: empty-dir
  annotations:
    resources: empty-dir
spec:
  containers:
    - image: nginx
      name: webserver
      volumeMounts:
        - mountPath: /emptydir
          name: empty-dir
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          cpu: "0.3"
          memory: "64Mi"
  volumes:
    - name: empty-dir
      emptyDir:
        sizeLimit: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
