apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    deploy: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: container-nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 265Mi
            requests:
              cpu: "0.3"
              memory: 65Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            # tcpSocket:
            # port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80/
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
