apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"deploy":"nginx"},"name":"deploy-nginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx","name":"container-nginx","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"0.5","memory":"265Mi"},"requests":{"cpu":"0.3","memory":"65Mi"}}}]}}}}
  creationTimestamp: "2024-03-01T19:33:29Z"
  generation: 4
  labels:
    deploy: nginx
  name: deploy-nginx
  namespace: default
  resourceVersion: "27546"
  uid: 9cf7c90f-0f02-4262-a71e-cd71d90ced13
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: container-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 265Mi
          requests:
            cpu: 300m
            memory: 65Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-03-01T19:37:59Z"
    lastUpdateTime: "2024-03-01T19:37:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-01T19:33:29Z"
    lastUpdateTime: "2024-03-01T22:28:21Z"
    message: ReplicaSet "deploy-nginx-78b9f6fff8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
