apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
    app: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
